### ISSUE TITLE
Minification of Object Properties

### ISSUE THREAD

**Issue by SunburnedGoose** [joshhunt/destinyPlumbing#1]
I've wondered how much benefit could be found by minifying the property names of the objects, and rehydrating them on the client.  Thoughts?

**Comment by joshhunt** [comment]
This is essentially done automatically with gzip already, so there would be very little gain doing this manually.

I thought about using something like [protobuf](https://github.com/google/protobuf) for this, but it [doesn't really seem worth it](https://blog.wearewizards.io/using-protobuf-instead-of-json-to-communicate-with-a-frontend).

Keeping in mind that the point of this project is to make data easier to consume, and lessen the need for app updates that use item data, I think gzip should be fine for a bit.
